### ISSUE TITLE
"Error while calling lua chunk for luaeval()... Undefined variable: _instruction"

### ISSUE THREAD

**Issue by chardskarth** [Iron-E/nvim-libmodal#8]
Awesome work @Iron-E! But it'd be best if I can make this work.

![image](https://user-images.githubusercontent.com/26249511/94369411-194b2800-011c-11eb-8bac-0b4863930311.png)

**Comment by Iron-E** [comment]
I transferred this issue to this repo since you're using `nvim-libmodal`.

Thanks for the clear version statements, that really helps :+1: 

As for the issue, I see this:

```lua
command! WindowMode call libmodal#Enter('Window', funcref('s:WindowMode'))
```

The lua-vim interface doesn't like to process `funcref`s. You can read more about that [here](https://github.com/Iron-E/nvim-libmodal/blob/master/doc/libmodal.txt#L148), but in short:

* The ability to resolve `funcref`s wasn't added until a recent 0.5 nightly.
* You can't directly pass the `funcref()` result, instead, you must pass the name of the function.

So the command would look like this:

```lua
command! WindowMode call libmodal#Enter('Window', 's:WindowMode')
```

Thought it won't work without 0.5.

The reason it works with `vim-libmodal` is that it is written entirely in Vimscript, so it never has to cross that barrier from Lua to Vim (and thus never has to deal with resolving the `funcref()`).

You can test this solution out by downloading Neovim 0.5 and replacing the `command` with the one I provided.

Let me know if it works!

**Comment by chardskarth** [comment]
I'll have to make do with using  `vim-libmodal` for now. 
Thank you very much. Closing this issue now.

PS I can't thank you enough for this plugin. This really helped me in my workflow!

**Comment by Iron-E** [comment]
Happy to help! I posted another solution that doesn't require 0.5, which you can take a look at.

In the meantime, feel free to open any additional tickets as necessary :+1:
